# Site settings
# minimal_mistakes_skin: "dirt"
locale: "en-US"

masthead_title: Songpoem
title: Songpoem Solutions LLP
subtitle: "We compose success"
email: sandesh.soni@songpoem.com
description: >- # this means to ignore newlines until "baseurl:"
  Lets Compose Success Together.
logo: "/assets/images/songpoemlabs-logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.songpoem.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: songpoemHQ
github_username: songpoemHQ
facebook_username: songpoemHQ

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
# permalink: /blog/:categories/:slug/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _posts/*/*
  - _pages
  - _services
  - _skills/core
  - _why-us
  - _why_us_human
  - _technologies

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-archives
  # - jekyll-postcss
  - jekyll-remote-theme
  - jekyll-tailwindcss
  - jekyll-paginate

sass:
  sass_dir: _sass
  style: compressed

# postcss:
#   cache: false

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/songpoemlabs"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-li-square"
      url: "https://linkedin.com/company/songpoemlabs"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/songpoemlabs"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/songpoemlabs"

collections:
  posts:
    permalink: /blog/:slug/
  portfolio:
    output: true
    permalink: /casestudies/:path/
  services:
    output: true
    permalink: /:collection/:path/
  skills:
    output: true
    permalink: /:collection/:path/
  why_us:
    output: true
    permalink: /:collection/:path/
  why_us_human:
    output: true
    permalink: /:collection/:path/
  tils:
    output: true
    permalink: /:collection/:name
  technologies:
    output: true
    permalink: /:collection/:name

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: "single"
      author_profile: false
  # - scope:
  #     path: "_technologies"
  #     type: technology
    # values:
    #   layout: single
    #   author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google"
  google:
    tracking_id: "G-GTYGD0GH2H"
    anonymize_ip: true

